// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'2d78ab1c4c32e92d53902b6cab52348af0dc644c2b12350d1836d016064b2225'>;
export type ExecutionHash =
  ExecutionHashBase<'9082aa9b0c758815136b47daca45378fd56fbb42f9eb054c50e7ec97e69e2edd'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Exercise: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly muscleGroup: CodecTypes['pg/text@1']['output'] | null;
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly ExerciseSession: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly workoutSessionId: CodecTypes['pg/uuid@1']['output'];
      readonly workoutExerciseId: CodecTypes['pg/uuid@1']['output'];
      readonly exerciseOrder: CodecTypes['pg/int4@1']['output'];
      readonly plannedSets: CodecTypes['pg/int4@1']['output'];
      readonly plannedReps: CodecTypes['pg/int4@1']['output'];
      readonly restSeconds: CodecTypes['pg/int4@1']['output'] | null;
      readonly completed: CodecTypes['pg/bool@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly ExerciseSet: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly exerciseSessionId: CodecTypes['pg/uuid@1']['output'];
      readonly setNumber: CodecTypes['pg/int4@1']['output'];
      readonly weight: CodecTypes['pg/numeric@1']['output'] | null;
      readonly reps: CodecTypes['pg/int4@1']['output'] | null;
      readonly completed: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Workout: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly WorkoutExercise: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly workoutId: CodecTypes['pg/uuid@1']['output'];
      readonly exerciseId: CodecTypes['pg/uuid@1']['output'];
      readonly exerciseOrder: CodecTypes['pg/int4@1']['output'];
      readonly plannedSets: CodecTypes['pg/int4@1']['output'];
      readonly plannedReps: CodecTypes['pg/int4@1']['output'];
      readonly restSeconds: CodecTypes['pg/int4@1']['output'] | null;
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly WorkoutSession: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly workoutId: CodecTypes['pg/uuid@1']['output'];
      readonly startedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly finishedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Exercise: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly muscleGroup: CodecTypes['pg/text@1']['input'] | null;
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly ExerciseSession: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly workoutSessionId: CodecTypes['pg/uuid@1']['input'];
      readonly workoutExerciseId: CodecTypes['pg/uuid@1']['input'];
      readonly exerciseOrder: CodecTypes['pg/int4@1']['input'];
      readonly plannedSets: CodecTypes['pg/int4@1']['input'];
      readonly plannedReps: CodecTypes['pg/int4@1']['input'];
      readonly restSeconds: CodecTypes['pg/int4@1']['input'] | null;
      readonly completed: CodecTypes['pg/bool@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly ExerciseSet: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly exerciseSessionId: CodecTypes['pg/uuid@1']['input'];
      readonly setNumber: CodecTypes['pg/int4@1']['input'];
      readonly weight: CodecTypes['pg/numeric@1']['input'] | null;
      readonly reps: CodecTypes['pg/int4@1']['input'] | null;
      readonly completed: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Workout: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly WorkoutExercise: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly workoutId: CodecTypes['pg/uuid@1']['input'];
      readonly exerciseId: CodecTypes['pg/uuid@1']['input'];
      readonly exerciseOrder: CodecTypes['pg/int4@1']['input'];
      readonly plannedSets: CodecTypes['pg/int4@1']['input'];
      readonly plannedReps: CodecTypes['pg/int4@1']['input'];
      readonly restSeconds: CodecTypes['pg/int4@1']['input'] | null;
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly WorkoutSession: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly workoutId: CodecTypes['pg/uuid@1']['input'];
      readonly startedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly finishedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly exercise_sessions: {
      readonly completed: CodecTypes['pg/bool@1']['output'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly exercise_order: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly planned_reps: CodecTypes['pg/int4@1']['output'];
      readonly planned_sets: CodecTypes['pg/int4@1']['output'];
      readonly rest_seconds: CodecTypes['pg/int4@1']['output'] | null;
      readonly workout_exercise_id: CodecTypes['pg/uuid@1']['output'];
      readonly workout_session_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly exercise_sets: {
      readonly completed: CodecTypes['pg/bool@1']['output'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly exercise_session_id: CodecTypes['pg/uuid@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly reps: CodecTypes['pg/int4@1']['output'] | null;
      readonly set_number: CodecTypes['pg/int4@1']['output'];
      readonly weight: CodecTypes['pg/numeric@1']['output'] | null;
    };
    readonly exercises: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly is_active: CodecTypes['pg/bool@1']['output'];
      readonly muscle_group: CodecTypes['pg/text@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly users: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly workout_exercises: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly exercise_id: CodecTypes['pg/uuid@1']['output'];
      readonly exercise_order: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly is_active: CodecTypes['pg/bool@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly planned_reps: CodecTypes['pg/int4@1']['output'];
      readonly planned_sets: CodecTypes['pg/int4@1']['output'];
      readonly rest_seconds: CodecTypes['pg/int4@1']['output'] | null;
      readonly workout_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly workout_sessions: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly finished_at: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly started_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly user_id: CodecTypes['pg/uuid@1']['output'];
      readonly workout_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly workouts: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly is_active: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly user_id: CodecTypes['pg/uuid@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly exercise_sessions: {
      readonly completed: CodecTypes['pg/bool@1']['input'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly exercise_order: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly planned_reps: CodecTypes['pg/int4@1']['input'];
      readonly planned_sets: CodecTypes['pg/int4@1']['input'];
      readonly rest_seconds: CodecTypes['pg/int4@1']['input'] | null;
      readonly workout_exercise_id: CodecTypes['pg/uuid@1']['input'];
      readonly workout_session_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly exercise_sets: {
      readonly completed: CodecTypes['pg/bool@1']['input'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly exercise_session_id: CodecTypes['pg/uuid@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly reps: CodecTypes['pg/int4@1']['input'] | null;
      readonly set_number: CodecTypes['pg/int4@1']['input'];
      readonly weight: CodecTypes['pg/numeric@1']['input'] | null;
    };
    readonly exercises: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly is_active: CodecTypes['pg/bool@1']['input'];
      readonly muscle_group: CodecTypes['pg/text@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly users: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly workout_exercises: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly exercise_id: CodecTypes['pg/uuid@1']['input'];
      readonly exercise_order: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly is_active: CodecTypes['pg/bool@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly planned_reps: CodecTypes['pg/int4@1']['input'];
      readonly planned_sets: CodecTypes['pg/int4@1']['input'];
      readonly rest_seconds: CodecTypes['pg/int4@1']['input'] | null;
      readonly workout_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly workout_sessions: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly finished_at: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly started_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly user_id: CodecTypes['pg/uuid@1']['input'];
      readonly workout_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly workouts: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly is_active: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly user_id: CodecTypes['pg/uuid@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly exercise_sessions: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly workout_session_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly workout_exercise_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly exercise_order: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly planned_sets: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly planned_reps: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly rest_seconds: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly completed: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly notes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['workout_session_id', 'workout_exercise_id'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'exercise_sessions_workout_session_id_idx_4025b05c';
                  readonly prefix: 'exercise_sessions_workout_session_id_idx';
                  readonly columns: readonly ['workout_session_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'exercise_sessions_workout_exercise_id_idx_e8bd1b8c';
                  readonly prefix: 'exercise_sessions_workout_exercise_id_idx';
                  readonly columns: readonly ['workout_exercise_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'exercise_sessions';
                    readonly columns: readonly ['workout_session_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'workout_sessions';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'exercise_sessions';
                    readonly columns: readonly ['workout_exercise_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'workout_exercises';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly exercise_sets: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly exercise_session_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly set_number: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly weight: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly reps: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly completed: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['exercise_session_id', 'set_number'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'exercise_sets_exercise_session_id_idx_f8a0614a';
                  readonly prefix: 'exercise_sets_exercise_session_id_idx';
                  readonly columns: readonly ['exercise_session_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'exercise_sets';
                    readonly columns: readonly ['exercise_session_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'exercise_sessions';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly exercises: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly muscle_group: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly is_active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'exercises_name_idx_ce87e6ba';
                  readonly prefix: 'exercises_name_idx';
                  readonly columns: readonly ['name'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly users: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly workout_exercises: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly workout_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly exercise_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly exercise_order: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly planned_sets: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly planned_reps: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly rest_seconds: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly notes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly is_active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['workout_id', 'exercise_order'] }];
              indexes: readonly [
                {
                  readonly name: 'workout_exercises_workout_id_idx_7b5dce6d';
                  readonly prefix: 'workout_exercises_workout_id_idx';
                  readonly columns: readonly ['workout_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'workout_exercises_exercise_id_idx_b01d81a7';
                  readonly prefix: 'workout_exercises_exercise_id_idx';
                  readonly columns: readonly ['exercise_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'workout_exercises_workout_id_is_active_idx_00f9ff08';
                  readonly prefix: 'workout_exercises_workout_id_is_active_idx';
                  readonly columns: readonly ['workout_id', 'is_active'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'workout_exercises';
                    readonly columns: readonly ['workout_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'workouts';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'workout_exercises';
                    readonly columns: readonly ['exercise_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'exercises';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly workout_sessions: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly workout_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly started_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly finished_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly notes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'workout_sessions_user_id_idx_6c952402';
                  readonly prefix: 'workout_sessions_user_id_idx';
                  readonly columns: readonly ['user_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'workout_sessions_workout_id_idx_7b5dce6d';
                  readonly prefix: 'workout_sessions_workout_id_idx';
                  readonly columns: readonly ['workout_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'workout_sessions_started_at_idx_bcc4bc60';
                  readonly prefix: 'workout_sessions_started_at_idx';
                  readonly columns: readonly ['started_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'workout_sessions_user_id_started_at_idx_beb66913';
                  readonly prefix: 'workout_sessions_user_id_started_at_idx';
                  readonly columns: readonly ['user_id', 'started_at'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'workout_sessions';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'workout_sessions';
                    readonly columns: readonly ['workout_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'workouts';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly workouts: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly notes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly is_active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'workouts_user_id_idx_6c952402';
                  readonly prefix: 'workouts_user_id_idx';
                  readonly columns: readonly ['user_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'workouts_user_id_is_active_idx_cacd3433';
                  readonly prefix: 'workouts_user_id_is_active_idx';
                  readonly columns: readonly ['user_id', 'is_active'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'workouts';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly users: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly exercises: { readonly namespace: 'public' & NamespaceId; readonly model: 'Exercise' };
    readonly workouts: { readonly namespace: 'public' & NamespaceId; readonly model: 'Workout' };
    readonly workout_exercises: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'WorkoutExercise';
    };
    readonly workout_sessions: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'WorkoutSession';
    };
    readonly exercise_sessions: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ExerciseSession';
    };
    readonly exercise_sets: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ExerciseSet';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Exercise: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly muscleGroup: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly workoutExercises: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'WorkoutExercise';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['exerciseId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'exercises';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly description: { readonly column: 'description' };
                readonly muscleGroup: { readonly column: 'muscle_group' };
                readonly isActive: { readonly column: 'is_active' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly ExerciseSession: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly workoutSessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly workoutExerciseId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly exerciseOrder: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly plannedSets: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly plannedReps: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly restSeconds: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly completed: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly notes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly sets: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ExerciseSet';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['exerciseSessionId'];
                };
              };
              readonly workoutExercise: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'WorkoutExercise';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['workoutExerciseId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly workoutSession: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'WorkoutSession';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['workoutSessionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'exercise_sessions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly workoutSessionId: { readonly column: 'workout_session_id' };
                readonly workoutExerciseId: { readonly column: 'workout_exercise_id' };
                readonly exerciseOrder: { readonly column: 'exercise_order' };
                readonly plannedSets: { readonly column: 'planned_sets' };
                readonly plannedReps: { readonly column: 'planned_reps' };
                readonly restSeconds: { readonly column: 'rest_seconds' };
                readonly completed: { readonly column: 'completed' };
                readonly notes: { readonly column: 'notes' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly ExerciseSet: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly exerciseSessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly setNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly weight: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly reps: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly completed: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly exerciseSession: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ExerciseSession';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['exerciseSessionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'exercise_sets';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly exerciseSessionId: { readonly column: 'exercise_session_id' };
                readonly setNumber: { readonly column: 'set_number' };
                readonly weight: { readonly column: 'weight' };
                readonly reps: { readonly column: 'reps' };
                readonly completed: { readonly column: 'completed' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly workoutSessions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'WorkoutSession';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly workouts: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Workout';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly Workout: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly notes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly workoutExercises: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'WorkoutExercise';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['workoutId'];
                };
              };
              readonly workoutSessions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'WorkoutSession';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['workoutId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'workouts';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'user_id' };
                readonly name: { readonly column: 'name' };
                readonly notes: { readonly column: 'notes' };
                readonly isActive: { readonly column: 'is_active' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly WorkoutExercise: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly workoutId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly exerciseId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly exerciseOrder: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly plannedSets: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly plannedReps: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly restSeconds: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly notes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly exercise: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Exercise';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['exerciseId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly exerciseSessions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ExerciseSession';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['workoutExerciseId'];
                };
              };
              readonly workout: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Workout';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['workoutId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'workout_exercises';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly workoutId: { readonly column: 'workout_id' };
                readonly exerciseId: { readonly column: 'exercise_id' };
                readonly exerciseOrder: { readonly column: 'exercise_order' };
                readonly plannedSets: { readonly column: 'planned_sets' };
                readonly plannedReps: { readonly column: 'planned_reps' };
                readonly restSeconds: { readonly column: 'rest_seconds' };
                readonly notes: { readonly column: 'notes' };
                readonly isActive: { readonly column: 'is_active' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly WorkoutSession: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly workoutId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly startedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly finishedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly notes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly exerciseSessions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ExerciseSession';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['workoutSessionId'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly workout: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Workout';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['workoutId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'workout_sessions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'user_id' };
                readonly workoutId: { readonly column: 'workout_id' };
                readonly startedAt: { readonly column: 'started_at' };
                readonly finishedAt: { readonly column: 'finished_at' };
                readonly notes: { readonly column: 'notes' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'exercise_sessions';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'exercise_sets';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'exercises';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'users';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'workout_exercises';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'workout_sessions';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'workouts';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
